### ISSUE TITLE
V2 Api has lot of issues

### ISSUE THREAD

**Issue by bhvarshn** [jerokpradeep/pya3#55]
Websocket not working 
unable to subscribe to BANKNIFTY option

simple code is not working 

strike = alice.get_instrument_for_fno(exch="NFO",
                                          symbol="BANKNIFTY",
                                          expiry_date="2022-09-29",
                                          is_fut=False,
                                          strike=39700,
                                          is_CE=False)

    print(strike)
    alice.subscribe(strike)

Error
Instrument(exchange='NFO', token=48740, symbol='BANKNIFTY', name='BANKNIFTY22SEP39700PE', expiry='2022-09-29', lot_size=25)
Traceback (most recent call last):
  File "C:/Users/bhvarshn/PycharmProjects/pythonProject/testcode/alicebluehistoricaldata.py", line 124, in <module>
    alice.subscribe(strike)
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\pya3\alicebluepy.py", line 723, in subscribe
    scripts=scripts+__instrument.exchange+"|"+str(__instrument.token)+"#"
AttributeError: 'str' object has no attribute 'exchange'

Process finished with exit code 1

Fix all issues on priority 

Develop API for previous version webepage is not opening 

https://develop-api.aliceblueonline.com/

**Comment by naveen2410** [comment]
bn_call = [alice.get_instrument_for_fno(exch="NFO", symbol = 'BANKNIFTY', expiry_date="2022-10-06", is_fut=False, strike=strike=36300, is_CE = True]
alice.subscribe(bn_call)

**Comment by Vignesh-Devoloper** [comment]
Hi @naveen2410 Still you facing the issue?

**Comment by naveen2410** [comment]
Yes, it's still not working. Thanks

**Comment by Vignesh-Devoloper** [comment]
Ok @naveen2410 . Try this below code and share the response. 
[- Websocket sample code](https://github.com/jerokpradeep/pya3_sample_codes/blob/main/pya3_websocket.py)

**Comment by naveen2410** [comment]
websocket run forever ended in exception, run_forever() got an unexpected
keyword argument 'ping_payload'

**Comment by naveen2410** [comment]
App.py file in websocket folder has this menthod without ping payload as
input

**Comment by Vignesh-Devoloper** [comment]
@naveen2410 may I know which version you using in pya3?
