### ISSUE TITLE
historical data api not working

### ISSUE THREAD

**Issue by bhvarshn** [jerokpradeep/pya3#60]
Hi I am using below code and historical data api is not working 

instrument = alice.get_instrument_by_symbol("NFO", "RELIANCE")
from_datetime = datetime.datetime.now() - datetime.timedelta(days=1)     # From last & days
to_datetime = datetime.datetime.now()                                    # To now
interval = "D"       # ["1", "D"]
indices = False      # For Getting index data
print(alice.get_historical(instrument, from_datetime, to_datetime, interval, indices))

Error 
C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/bhvarshn/PycharmProjects/pythonProject/AliceblueV2apisupport/Testcode/historicaldata.py
Traceback (most recent call last):
  File "C:/Users/bhvarshn/PycharmProjects/pythonProject/AliceblueV2apisupport/Testcode/historicaldata.py", line 174, in <module>
    print(alice.get_historical(instrument, from_datetime, to_datetime, interval, indices))
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\pya3\alicebluepy.py", line 831, in get_historical
    lst = requests.get(f"https://a3.aliceblueonline.com/rest/AliceBlueAPIService/chart/history?", params=params).json()
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\bhvarshn\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\bhvarshn\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\bhvarshn\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

**Comment by bhvarshn** [comment]
team please reply

**Comment by Vignesh-Devoloper** [comment]
Hi @bhvarshn have you tested now?

**Comment by bhvarshn** [comment]
this api was working last week in market hours also. Can you please help to understand what you mean by " Data only available in Non Market hours"
I was testing my algo tool and it was perfectly working in market hours and in non market hours. Not sure what you guys changed after that it stopped working. Please clarify how to fetch historical data  .This is urgent. Thanks

**Comment by bhvarshn** [comment]
Team please reply this is urgent
