### ISSUE TITLE
Historical data api again stopped working during market hours

### ISSUE THREAD

**Issue by bhvarshn** [jerokpradeep/pya3#69]
C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\Scripts\python.exe "C:/Users/bhvarshn/PycharmProjects/pythonProject/Chartinkbrahmastrabuycode/historical data.py"
NOTE: Today's contract master file will be updated after 08:00 AM. Before 08:00 AM previous day contract file be downloaded.
Traceback (most recent call last):
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\bhvarshn\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\bhvarshn\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\bhvarshn\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/bhvarshn/PycharmProjects/pythonProject/Chartinkbrahmastrabuycode/historical data.py", line 14, in <module>
    print(alice.get_historical(instrument, from_datetime, to_datetime, interval, indices))
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\pya3\alicebluepy.py", line 843, in get_historical
    response=lst.json()
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by overdoseod** [comment]
while True:
        try:
            df=alice.get_historical(instrument, from_datetime, to_datetime, interval, indices)
            break
        except:
            print('Error fetching historical data')
            time.sleep(5)
            pass
try this to bypass the error
this is not the permanent solution but it will bypass the error so that the script doesnt stop

**Comment by yashsonwane** [comment]
How to pass different interval in historical data.
I can use only 1 and D i.e 1 min and day interval but i like to use more than this 
like 3 min, 5 min, 10 min 15 min , 1 hour , 2 hour, how should I write for this interval??
