### ISSUE TITLE
Historical data is not working 

### ISSUE THREAD

**Issue by monasingh05** [jerokpradeep/pya3#82]
Hello, 

I tried to access historical data but error appears 

from datetime import datetime
from datetime import timedelta
from pya3 import *

alice = Aliceblue(user_id='*****',api_key='*****')

instrument = alice.get_instrument_by_symbol("NSE", "RELIANCE")

from_datetime = datetime.now() - timedelta(days=3)     # From last & days
to_datetime = datetime.now()                                    # To now
interval = "1"       # ["1", "D"]
indices = False      # For Getting index data
print(alice.get_historical(instrument, from_datetime, to_datetime, interval, indices))

Error appears : 
Traceback (most recent call last):
  File "C:\Users\91704\PycharmProjects\algo_t_1\venv\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\91704\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\91704\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\91704\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\91704\PycharmProjects\algo_t_1\1.py", line 18, in <module>
    print(alice.get_historical(instrument, from_datetime, to_datetime, interval, indices))
  File "C:\Users\91704\PycharmProjects\algo_t_1\venv\lib\site-packages\pya3\alicebluepy.py", line 843, in get_historical
    response=lst.json()
  File "C:\Users\91704\PycharmProjects\algo_t_1\venv\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] Unauthorized: 0

Process finished with exit code 1

**Comment by jayaraj007007** [comment]
need to get session Id before fetch data.
Try this.

from datetime import datetime
from datetime import timedelta
from pya3 import *

alice = Aliceblue(user_id='',api_key='')

instrument = alice.get_instrument_by_symbol("NSE", "RELIANCE")
alice.get_session_id()
from_datetime = datetime.now() - timedelta(days=3) # From last & days
to_datetime = datetime.now() # To now
interval = "1" # ["1", "D"]
indices = False # For Getting index data
print(alice.get_historical(instrument, from_datetime, to_datetime, interval, indices))

**Comment by monasingh05** [comment]
Thank you ....its working now
